In [1]:
import pandas
print(pandas.__version__)

3.0.3

DATA STRUCTURES

In [2]:
import pandas as pd

s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

In [3]:
import pandas as pd

df = pd.DataFrame([10, 20, 30])
df

    0
0  10
1  20
2  30

In [19]:
import pandas as pd
df = pd.read_excel(r'C:\Users\Admin\Downloads\weather_data_XL.xlsx')
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [20]:
df.to_excel(r'C:\Users\Admin\Downloads\new.xlsx', index=False)
print("File saved successfully!")

File saved successfully!

In [21]:
print(df)
print(df.shape)

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny
(10, 5)

In [7]:
df.head()

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny
2 2025-01-03  Hyderbad             30          58    Cloudy
3 2025-01-04  Hyderbad             31          55    Cloudy
4 2025-01-05  Banglore             32          57     Rainy

In [8]:
df.head(8)

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny
2 2025-01-03  Hyderbad             30          58    Cloudy
3 2025-01-04  Hyderbad             31          55    Cloudy
4 2025-01-05  Banglore             32          57     Rainy
5 2025-01-06  Banglore             33          59     Rainy
6 2025-01-07  Banglore             34          61     Sunny
7 2025-01-08  Banglore             32          63    Cloudy

In [9]:
df.tail()

        Date        City  Temperature_C  Humidity_% Condition
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [10]:
df.tail(5)

        Date        City  Temperature_C  Humidity_% Condition
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           10 non-null     datetime64[us]
 1   City           10 non-null     str
 2   Temperature_C  10 non-null     int64
 3   Humidity_%     10 non-null     int64
 4   Condition      10 non-null     str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 532.0 bytes

In [12]:
df['Date']

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[us]

In [13]:
df.shape

(10, 5)

In [14]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='str')

In [15]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [24]:
df[['Date', 'Condition']]

        Date Condition
0 2025-01-01     Sunny
1 2025-01-02     Sunny
2 2025-01-03    Cloudy
3 2025-01-04    Cloudy
4 2025-01-05     Rainy
5 2025-01-06     Rainy
6 2025-01-07     Sunny
7 2025-01-08    Cloudy
8 2025-01-09     Rainy
9 2025-01-10     Sunny

In [25]:
df.isnull()

    Date   City  Temperature_C  Humidity_%  Condition
0  False  False          False       False      False
1  False  False          False       False      False
2  False  False          False       False      False
3  False  False          False       False      False
4  False  False          False       False      False
5  False  False          False       False      False
6  False  False          False       False      False
7  False  False          False       False      False
8  False  False          False       False      False
9  False  False          False       False      False

In [26]:
df.isnull().sum()

Date             0
City             0
Temperature_C    0
Humidity_%       0
Condition        0
dtype: int64

In [71]:
df=pd.DataFrame({
    'name':["hari","hima","nani"],
    'age':[20,21,None]
})
df

   name   age
0  hari  20.0
1  hima  21.0
2  nani   NaN

In [72]:
df['age']=df['age'].fillna(df['age'].mean())
df

   name   age
0  hari  20.0
1  hima  21.0
2  nani  20.5

In [73]:
df['age']=df['age'].fillna(0)
df

   name   age
0  hari  20.0
1  hima  21.0
2  nani  20.5

In [2]:
import pandas as pd
df=pd.DataFrame({
    "name":["harshi","ganna","ganna"],
    "reg":[577,588,588]
})
df

     name  reg
0  harshi  577
1   ganna  588
2   ganna  588

In [3]:
df.duplicated ()#to check duplicate values

0    False
1    False
2     True
dtype: bool

In [4]:
df=df.drop_duplicates()
df

     name  reg
0  harshi  577
1   ganna  588

In [44]:
df = pd.read_excel(r'C:\Users\Admin\Downloads\weather_data_XL.xlsx')
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [45]:
df['Temperature_C'].std()

np.float64(1.911950719959998)

In [46]:
df['Temperature_C'].var()

np.float64(3.6555555555555554)

In [47]:
df['Temperature_C'].min()

np.int64(28)

In [49]:
df['Temperature_C'].max()

np.int64(34)

In [51]:
df['Temperature_C'].mean()

np.float64(30.9)

In [52]:
df['Temperature_C'].describe()

count    10.000000
mean     30.900000
std       1.911951
min      28.000000
25%      29.250000
50%      31.000000
75%      32.000000
max      34.000000
Name: Temperature_C, dtype: float64

In [54]:
df[df.Temperature_C ==df.Temperature_C.max()]

        Date      City  Temperature_C  Humidity_% Condition
6 2025-01-07  Banglore             34          61     Sunny

In [57]:
df.City[df.Temperature_C ==df.Temperature_C.max()]

6    Banglore
Name: City, dtype: str

In [58]:
df.Date[df.Temperature_C ==df.Temperature_C.max()]

6   2025-01-07
Name: Date, dtype: datetime64[us]

In [59]:
df.count()

Date             10
City             10
Temperature_C    10
Humidity_%       10
Condition        10
dtype: int64

In [60]:
df["City"].nunique()

3

In [61]:
df["City"].value_counts()

City
Hyderbad      4
Banglore      4
Vijayawada    2
Name: count, dtype: int64

string cleaning

In [62]:
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [67]:
df["City"] = df["City"].str.lower()
df

        Date        City  Temperature_C  Humidity_% Condition        city
0 2025-01-01    hyderbad             28          60     Sunny    hyderbad
1 2025-01-02    hyderbad             29          62     Sunny    hyderbad
2 2025-01-03    hyderbad             30          58    Cloudy    hyderbad
3 2025-01-04    hyderbad             31          55    Cloudy    hyderbad
4 2025-01-05    banglore             32          57     Rainy    banglore
5 2025-01-06    banglore             33          59     Rainy    banglore
6 2025-01-07    banglore             34          61     Sunny    banglore
7 2025-01-08    banglore             32          63    Cloudy    banglore
8 2025-01-09  vijayawada             31          64     Rainy  vijayawada
9 2025-01-10  vijayawada             29          62     Sunny  vijayawada

In [68]:
df["City"] = df["City"].str.upper()
df

        Date        City  Temperature_C  Humidity_% Condition        city
0 2025-01-01    HYDERBAD             28          60     Sunny    hyderbad
1 2025-01-02    HYDERBAD             29          62     Sunny    hyderbad
2 2025-01-03    HYDERBAD             30          58    Cloudy    hyderbad
3 2025-01-04    HYDERBAD             31          55    Cloudy    hyderbad
4 2025-01-05    BANGLORE             32          57     Rainy    banglore
5 2025-01-06    BANGLORE             33          59     Rainy    banglore
6 2025-01-07    BANGLORE             34          61     Sunny    banglore
7 2025-01-08    BANGLORE             32          63    Cloudy    banglore
8 2025-01-09  VIJAYAWADA             31          64     Rainy  vijayawada
9 2025-01-10  VIJAYAWADA             29          62     Sunny  vijayawada

In [69]:
df["City"]=df["City"].str.replace("HYDERBAD","CHENNAI")
df

        Date        City  Temperature_C  Humidity_% Condition        city
0 2025-01-01     CHENNAI             28          60     Sunny    hyderbad
1 2025-01-02     CHENNAI             29          62     Sunny    hyderbad
2 2025-01-03     CHENNAI             30          58    Cloudy    hyderbad
3 2025-01-04     CHENNAI             31          55    Cloudy    hyderbad
4 2025-01-05    BANGLORE             32          57     Rainy    banglore
5 2025-01-06    BANGLORE             33          59     Rainy    banglore
6 2025-01-07    BANGLORE             34          61     Sunny    banglore
7 2025-01-08    BANGLORE             32          63    Cloudy    banglore
8 2025-01-09  VIJAYAWADA             31          64     Rainy  vijayawada
9 2025-01-10  VIJAYAWADA             29          62     Sunny  vijayawada